### ISSUE TITLE
"X11/Intrinsic.h" error while compiling

### ISSUE THREAD

**Issue by zongy17** [AMReX-Codes/Amrvis#29]
Hi, I am new to AMReX and Amrvis, and following the guided tutorials step-by-step.

When I am trying to build the visualization tool, Amrvis, it reports an error that "X11/Intrinsic.h" referenced at ./AmrPicture.H:24:10 could not be found. The detailed output is:

> [zongyi@kunpeng-master:~/HUAWEI/software-package/Amrvis-main]$ make DIM=2
fatal: Not a git repository (or any parent up to mount point /storage)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Loading /storage/hpcauser/zongyi/HUAWEI/software-package/amrex-24.01/Tools/GNUMake/comps/gnu.mak...
Loading /storage/hpcauser/zongyi/HUAWEI/software-package/amrex-24.01/Tools/GNUMake/sites/Make.unknown...
/storage/hpcauser/zongyi/HUAWEI/software-package/amrex-24.01/Tools/GNUMake/Make.rules:505: tmp_build_dir/d/2d.gnu.MPI.EXE/f90.depends: No such file or directory
Generating AMReX_Config.H ...
Generating AMReX_Version.H ...
Building f90/F90 dependency File ...
/storage/hpcauser/zongyi/HUAWEI/software-package/amrex-24.01/Tools/F_scripts/dep.py  --prefix tmp_build_dir/o/2d.gnu.MPI.EXE \
            --temp_dir tmp_build_dir/f/2d.gnu.MPI.EXE \
            --cpp "cpp -E -traditional-cpp -P" \
            --defines "-DBL_LANG_FORT -DAMREX_LANG_FORT  -DBL_USE_MPI -DAMREX_USE_MPI -DBL_USE_ARRAYVIEW -DAMREX_USE_ARRAYVIEW -DAMREX_GPU_MAX_THREADS=0 -DBL_SPACEDIM=2 -DAMREX_SPACEDIM=2 -DBL_FORT_USE_UNDERSCORE -DAMREX_FORT_USE_UNDERSCORE -DBL_Linux -DAMREX_Linux -DNDEBUG -DOMPI_SKIP_MPICXX -DBL_OPTIO -DBL_USE_ARRAYVIEW -Itmp_build_dir/s/2d.gnu.MPI.EXE -I. -I. -I. -I/storage/hpcauser/zongyi/HUAWEI/software-package/amrex-24.01/Src/Base -I/storage/hpcauser/zongyi/HUAWEI/software-package/amrex-24.01/Src/Extern/amrdata -I/usr/include/ -I/usr/include/Xm -I. -I/storage/hpcauser/zongyi/HUAWEI/software-package/amrex-24.01/Src/Base -I/storage/hpcauser/zongyi/HUAWEI/software-package/amrex-24.01/Src/Base/Parser -I/storage/hpcauser/zongyi/HUAWEI/software-package/amrex-24.01/Src/Extern/amrdata " \
            --f90_preprocess "cat  " /storage/hpcauser/zongyi/HUAWEI/software-package/amrex-24.01/Src/Base/AMReX_constants_mod.f90 /storage/hpcauser/zongyi/HUAWEI/software-package/amrex-24.01/Src/Base/AMReX_FILCC_2D.F90 /storage/hpcauser/zongyi/HUAWEI/software-package/amrex-24.01/Src/Base/AMReX_BLutil_F.F90 /storage/hpcauser/zongyi/HUAWEI/software-package/amrex-24.01/Src/Base/AMReX_BLProfiler_F.F90 /storage/hpcauser/zongyi/HUAWEI/software-package/amrex-24.01/Src/Base/AMReX_filcc_mod.F90 /storage/hpcauser/zongyi/HUAWEI/software-package/amrex-24.01/Src/Base/AMReX_omp_mod.F90 /storage/hpcauser/zongyi/HUAWEI/software-package/amrex-24.01/Src/Base/AMReX_acc_mod.F90 /storage/hpcauser/zongyi/HUAWEI/software-package/amrex-24.01/Src/Base/AMReX_fort_mod.F90 /storage/hpcauser/zongyi/HUAWEI/software-package/amrex-24.01/Src/Base/AMReX_error_mod.F90 /storage/hpcauser/zongyi/HUAWEI/software-package/amrex-24.01/Src/Base/AMReX_parmparse_mod.F90 /storage/hpcauser/zongyi/HUAWEI/software-package/amrex-24.01/Src/Base/AMReX_string_mod.F90 /storage/hpcauser/zongyi/HUAWEI/software-package/amrex-24.01/Src/Base/AMReX_bc_types_mod.F90 /storage/hpcauser/zongyi/HUAWEI/software-package/amrex-24.01/Src/Base/AMReX_io_mod.F90 /storage/hpcauser/zongyi/HUAWEI/software-package/amrex-24.01/Src/Base/AMReX_ParallelDescriptor_F.F90 /storage/hpcauser/zongyi/HUAWEI/software-package/amrex-24.01/Src/Base/AMReX_mempool_mod.F90 tmp_build_dir/s/2d.gnu.MPI.EXE/AMReX_Config.H tmp_build_dir/s/2d.gnu.MPI.EXE/AMReX_Version.H > tmp_build_dir/d/2d.gnu.MPI.EXE/f90.depends
Depending /storage/hpcauser/zongyi/HUAWEI/software-package/amrex-24.01/Src/Extern/amrdata/AMReX_FABUTIL_2D.F ...
/usr/include/Xm does not exist
fatal: Not a git repository (or any parent up to mount point /storage)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Loading /storage/hpcauser/zongyi/HUAWEI/software-package/amrex-24.01/Tools/GNUMake/comps/gnu.mak...
Loading /storage/hpcauser/zongyi/HUAWEI/software-package/amrex-24.01/Tools/GNUMake/sites/Make.unknown...
Compiling AmrPicture.cpp ...
mpicxx -MMD -MP  -Werror=return-type -g -O3 -std=c++17  -pthread    -DBL_USE_MPI -DAMREX_USE_MPI -DBL_USE_ARRAYVIEW -DAMREX_USE_ARRAYVIEW -DAMREX_GPU_MAX_THREADS=0 -DBL_SPACEDIM=2 -DAMREX_SPACEDIM=2 -DBL_FORT_USE_UNDERSCORE -DAMREX_FORT_USE_UNDERSCORE -DBL_Linux -DAMREX_Linux -DNDEBUG -DOMPI_SKIP_MPICXX -DBL_OPTIO -DBL_USE_ARRAYVIEW -Itmp_build_dir/s/2d.gnu.MPI.EXE -I. -I. -I. -I/storage/hpcauser/zongyi/HUAWEI/software-package/amrex-24.01/Src/Base -I/storage/hpcauser/zongyi/HUAWEI/software-package/amrex-24.01/Src/Extern/amrdata -I/usr/include/ -I/usr/include/Xm -I. -I/storage/hpcauser/zongyi/HUAWEI/software-package/amrex-24.01/Src/Base -I/storage/hpcauser/zongyi/HUAWEI/software-package/amrex-24.01/Src/Base/Parser -I/storage/hpcauser/zongyi/HUAWEI/software-package/amrex-24.01/Src/Extern/amrdata  -isystem /storage/software/libs/hccSPC010B010/hpcx/2.7.0/openmpi/include/openmpi -isystem /storage/software/libs/hccSPC010B010/hpcx/2.7.0/openmpi/include/openmpi/opal/mca/hwloc/hwloc201/hwloc/include -isystem /storage/software/libs/hccSPC010B010/hpcx/2.7.0/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent -isystem /storage/software/libs/hccSPC010B010/hpcx/2.7.0/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent/include -isystem /storage/software/libs/hccSPC010B010/hpcx/2.7.0/openmpi/include -c AmrPicture.cpp -o tmp_build_dir/o/2d.gnu.MPI.EXE/AmrPicture.o
In file included from AmrPicture.cpp:6:
./AmrPicture.H:24:10: fatal error: X11/Intrinsic.h: No such file or directory
   24 | #include <X11/Intrinsic.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [tmp_build_dir/o/2d.gnu.MPI.EXE/AmrPicture.o] Error 1

It looks like I should add something that Amrvis requires first. But I don't know what it is and where I should modify the makefile. Could you help me to fix it?

**Comment by asalmgren** [comment]
It sounds like you don't have X11 on your machine.  Can you find it?

**Comment by zongy17** [comment]
Yes, I fixed it. But a new error occurs when linking:

> /storage/software/compiler/gcc/9.3.1/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: tmp_build_dir/o/2d.gnu.EXE/AmrVisTool.o: in function `NeverCalled()':
/storage/hpcauser/zongyi/HUAWEI/software-package/Amrvis-main/./ArrayView.H:17: multiple definition of `NeverCalled()'; tmp_build_dir/o/2d.gnu.EXE/AmrPicture.o:/storage/hpcauser/zongyi/HUAWEI/software-package/Amrvis-main/./ArrayView.H:17: first defined here
/storage/software/compiler/gcc/9.3.1/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: cannot find -larrayview2d
/storage/software/compiler/gcc/9.3.1/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: cannot find -lXpm
collect2: error: ld returned 1 exit status
make: *** [amrvis2d.gnu.ex] Error 1

It looks like the function "NeverCalled()" is multiple defined.

**Comment by WeiqunZhang** [comment]
What do you see with `git log` and `git status` in Amrvis? It seems that there are some local changes.

**Comment by zongy17** [comment]
Thanks for you advice! I re-downloaded the repo, and only changed `AMREX_HOME` in the GNUMakefile, then tried `make DIM=2` directly. This time it worked! Last time I commented some lines in the GNUMakefile (e.g., PRECISION=FLOAT, COMP=intel,  ...), and that may cause the compilation failure. Thanks!
